# Generated by Django 4.2.6 on 2024-04-23 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_filetype_orderfile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderfile",
            name="file_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="file_type",
                to="base.filetype",
            ),
        ),
    ]
