# Generated by Django 4.2.6 on 2024-04-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0006_alter_order_payment_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="market_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="Market price",
            ),
        ),
    ]
