# Generated by Django 4.2.6 on 2024-05-12 09:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0008_trailer_truck_driver_profile_truck_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="truck",
            name="model",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
