# Generated by Django 4.2.6 on 2024-06-03 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0009_truck_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="driver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="base.driver",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="truck",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="base.truck",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="base.tasktype",
            ),
        ),
    ]
