[uwsgi]
# Корневая папка проекта (полный путь)
chdir = /home/kubrakiv/malog/malog-app/current/

# Django wsgi файл
module = backend.wsgi:application
env = DJANGO_SETTINGS_MODULE=backend.env.production

home = /home/kubrakiv/malog/malog-app/shared/venv
plugin = python3

master = true

# Максимальное количество процессов
processes = 10
# Полный путь к файлу сокета
socket = /run/uwsgi/malog.sock

# run uWSGI as the www-data user and group
uid = www-data
gid = www-data

# права доступа к файлу сокета
chmod-socket = 666

# socket ownership (this line ensures www-data owns the socket)
chown-socket = www-data:www-data

# очищать окружение от служебных файлов uwsgi по завершению
vacuum = true
die-on-term = true

# Логи для uwsgi
logto = /var/log/uwsgi/malog_uwsgi.log
