# Generated by Django 4.2.6 on 2024-04-27 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profile", "0002_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
