# Generated by Django 4.2.6 on 2024-05-03 21:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profile", "0003_user_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="driverprofile",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="country",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="finished_work",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="first_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="full_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="last_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="driverprofile",
            name="started_work",
            field=models.DateField(blank=True, null=True),
        ),
    ]
