# Generated by Django 4.2.6 on 2024-05-07 22:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profile", "0005_driverprofile_license_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="driverprofile",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
