# Generated by Django 4.2.6 on 2024-05-08 22:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profile", "0006_driverprofile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="driverprofile",
            name="middle_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
