# Generated by Django 4.2.6 on 2025-10-06 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FuelPrices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "diesel_price_per_liter",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Current diesel price per liter in EUR",
                        max_digits=6,
                        verbose_name="Diesel Price per Liter",
                    ),
                ),
                (
                    "adblue_price_per_liter",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Current AdBlue price per liter in EUR",
                        max_digits=6,
                        verbose_name="AdBlue Price per Liter",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="EUR",
                        help_text="Currency for the prices",
                        max_length=3,
                        verbose_name="Currency",
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        default=True,
                        help_text="Mark as current fuel prices",
                        verbose_name="Current Prices",
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(
                        help_text="Date when these prices become effective",
                        verbose_name="Effective Date",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Fuel Prices",
                "verbose_name_plural": "Fuel Prices",
                "ordering": ["-effective_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RouteCalculation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "carrier",
                    models.CharField(
                        blank=True,
                        help_text="Name of the carrier company",
                        max_length=255,
                        null=True,
                        verbose_name="Company",
                    ),
                ),
                (
                    "customer",
                    models.CharField(
                        blank=True,
                        help_text="Name of the customer company",
                        max_length=255,
                        null=True,
                        verbose_name="Customer",
                    ),
                ),
                (
                    "empty_distance_km",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "loaded_distance_km",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                (
                    "total_duration_h",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("UAH", "Ukrainian Hryvnia"),
                            ("CZK", "Czech Koruna"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "diesel_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "adblue_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "fuel_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "tire_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "direct_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "toll_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "fixed_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "margin",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "margin_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "profit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "profit_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
            ],
            options={
                "verbose_name": "Route Calculation",
                "verbose_name_plural": "Route Calculations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TruckParameters",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., '20-ton Standard Tautliner'",
                        max_length=100,
                        verbose_name="Truck Type Name",
                    ),
                ),
                (
                    "weight_capacity",
                    models.PositiveIntegerField(
                        help_text="Maximum weight capacity in tons",
                        verbose_name="Weight Capacity (tons)",
                    ),
                ),
                (
                    "truck_type",
                    models.CharField(
                        help_text="e.g., 'Tautliner', 'Refrigerator', 'Container'",
                        max_length=50,
                        verbose_name="Truck Type",
                    ),
                ),
                (
                    "diesel_consumption_per_100km",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Diesel consumption in liters per 100 kilometers",
                        max_digits=5,
                        verbose_name="Diesel Consumption per 100km",
                    ),
                ),
                (
                    "adblue_consumption_per_100km",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="AdBlue consumption in liters per 100 kilometers",
                        max_digits=5,
                        verbose_name="AdBlue Consumption per 100km",
                    ),
                ),
                (
                    "tire_cost_per_km",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Tire wear cost per kilometer in EUR",
                        max_digits=8,
                        verbose_name="Tire Cost per km",
                    ),
                ),
                (
                    "fixed_cost_per_km",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Fixed costs (insurance, maintenance, etc.) per kilometer in EUR",
                        max_digits=8,
                        verbose_name="Fixed Cost per km",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Use as default truck parameters",
                        verbose_name="Default Parameters",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        help_text="Client that owns this record",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Truck Parameters",
                "verbose_name_plural": "Truck Parameters",
                "ordering": ["weight_capacity", "truck_type"],
            },
        ),
        migrations.CreateModel(
            name="RouteToll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("country", models.CharField(max_length=3)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                            ("UAH", "Ukrainian Hryvnia"),
                            ("CZK", "Czech Koruna"),
                        ],
                        default="EUR",
                        max_length=3,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount of toll in the specified currency",
                        max_digits=10,
                        verbose_name="Toll Amount",
                    ),
                ),
                (
                    "distance_km",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "client",
                    models.ForeignKey(
                        help_text="Client that owns this record",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.client",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tolls",
                        to="route_calculator.routecalculation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RoutePoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("country", models.CharField(blank=True, max_length=3, null=True)),
                ("postal_code", models.CharField(blank=True, max_length=20, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("label", models.CharField(blank=True, max_length=255, null=True)),
                ("date_from", models.DateField(blank=True, null=True)),
                ("date_to", models.DateField(blank=True, null=True)),
                (
                    "lat",
                    models.FloatField(
                        help_text="Latitude of the location", verbose_name="Latitude"
                    ),
                ),
                (
                    "lng",
                    models.FloatField(
                        help_text="Longitude of the location", verbose_name="Longitude"
                    ),
                ),
                (
                    "customer",
                    models.CharField(
                        blank=True,
                        help_text="Name of the customer company",
                        max_length=255,
                        null=True,
                        verbose_name="Customer",
                    ),
                ),
                (
                    "point_type",
                    models.CharField(
                        choices=[
                            ("start", "Start"),
                            ("loading", "Loading"),
                            ("unloading", "Unloading"),
                        ],
                        max_length=20,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "client",
                    models.ForeignKey(
                        help_text="Client that owns this record",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.client",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="points",
                        to="route_calculator.routecalculation",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
