# Generated by Django 4.2.6 on 2025-10-06 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("route_calculator", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("base", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="routecalculation",
            name="calculated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="route_calculations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="routecalculation",
            name="client",
            field=models.ForeignKey(
                help_text="Client that owns this record",
                on_delete=django.db.models.deletion.CASCADE,
                to="base.client",
            ),
        ),
        migrations.AddField(
            model_name="routecalculation",
            name="truck_parameters",
            field=models.ForeignKey(
                blank=True,
                help_text="Truck parameters used for cost calculation",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="route_calculator.truckparameters",
                verbose_name="Truck Parameters",
            ),
        ),
        migrations.AddField(
            model_name="fuelprices",
            name="client",
            field=models.ForeignKey(
                help_text="Client that owns this record",
                on_delete=django.db.models.deletion.CASCADE,
                to="base.client",
            ),
        ),
    ]
