# Generated by Django 4.2.6 on 2025-10-06 22:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_subscriptionplan_clientsubscription_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionplan",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
