# Generated by Django 4.2.6 on 2025-10-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0005_subscriptionplanchangerequest"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="subscriptionplanchangerequest",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="subscriptionplanchangerequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "pending")),
                fields=("client",),
                name="unique_pending_request_per_client",
            ),
        ),
    ]
