# Generated by Django 4.2.6 on 2025-10-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0006_alter_subscriptionplanchangerequest_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="clientsubscription",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="clientsubscription",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("client",),
                name="unique_active_subscription_per_client",
            ),
        ),
    ]
