# Generated by Django 4.2.6 on 2025-10-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0007_alter_clientsubscription_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="is_trial_plan",
            field=models.BooleanField(default=False, help_text="Is this a trial plan?"),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="trial_duration_days",
            field=models.IntegerField(
                default=14, help_text="Trial duration in days (for trial plans)"
            ),
        ),
        migrations.AlterField(
            model_name="clientsubscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("trial", "Trial"),
                    ("trial_expired", "Trial Expired"),
                    ("cancelled", "Cancelled"),
                    ("expired", "Expired"),
                    ("pending", "Pending Payment"),
                ],
                default="active",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionplan",
            name="name",
            field=models.CharField(
                choices=[
                    ("trial", "Trial Plan"),
                    ("base", "Base Plan"),
                    ("pro", "Pro Plan"),
                    ("unlimited", "Unlimited Plan"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
