# Generated by Django 5.2.7 on 2025-10-19 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0008_add_trial_support"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="is_onboarded",
            field=models.BooleanField(
                default=False, help_text="Client has completed the onboarding wizard"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="onboarded_at",
            field=models.DateTimeField(
                blank=True, help_text="When the client completed onboarding", null=True
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="planner_tutorial_shown",
            field=models.BooleanField(
                default=False,
                help_text="Planner tutorial has been shown to client users",
            ),
        ),
    ]
