# Generated by Django 5.2.7 on 2026-01-29 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0009_add_onboarding_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalAPIKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        db_index=True,
                        help_text="The API key (auto-generated)",
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Descriptive name for this API key (e.g., 'YouScore Integration', 'Mobile App')",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Additional details about this API key and its usage",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this API key is currently active and can be used",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Optional expiration date for this API key",
                        null=True,
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time this API key was used",
                        null=True,
                    ),
                ),
                (
                    "usage_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of times this API key has been used",
                    ),
                ),
                (
                    "rate_limit",
                    models.IntegerField(
                        default=100,
                        help_text="Maximum number of requests per hour (0 = unlimited)",
                    ),
                ),
                (
                    "allowed_endpoints",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of endpoint patterns this key can access (empty = all endpoints)",
                    ),
                ),
                (
                    "ip_whitelist",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of IP addresses allowed to use this key (empty = any IP)",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this API key",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_api_keys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "External API Key",
                "verbose_name_plural": "External API Keys",
                "ordering": ["-created_at"],
            },
        ),
    ]
