# Generated by Django 5.2.7 on 2026-01-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0010_add_external_api_key_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externalapikey",
            name="allowed_endpoints",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of endpoint patterns this key can access (empty = all endpoints)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="externalapikey",
            name="ip_whitelist",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of IP addresses allowed to use this key (empty = any IP)",
                null=True,
            ),
        ),
    ]
