# Generated by Django 5.2.7 on 2026-06-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0014_company_name_en"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientsubscription",
            name="pricing_model",
            field=models.CharField(
                choices=[("total", "Per Plan"), ("per_truck", "Per Truck")],
                default="total",
                max_length=10,
            ),
        ),
    ]
