# Generated by Django 5.2.7 on 2026-06-18 09:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0016_truck_trailer_sovtes_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="approval_status",
        ),
        migrations.RemoveField(
            model_name="client",
            name="approved_at",
        ),
        migrations.RemoveField(
            model_name="client",
            name="approved_by",
        ),
        migrations.RemoveField(
            model_name="client",
            name="is_approved",
        ),
        migrations.RemoveField(
            model_name="client",
            name="is_onboarded",
        ),
        migrations.RemoveField(
            model_name="client",
            name="onboarded_at",
        ),
        migrations.RemoveField(
            model_name="client",
            name="planner_tutorial_shown",
        ),
        migrations.RemoveField(
            model_name="client",
            name="rejection_reason",
        ),
        migrations.RemoveField(
            model_name="company",
            name="legal_address",
        ),
        migrations.RemoveField(
            model_name="company",
            name="name_en",
        ),
        migrations.RemoveField(
            model_name="trailer",
            name="sovtes_id",
        ),
        migrations.RemoveField(
            model_name="truck",
            name="sovtes_id",
        ),
        migrations.AlterField(
            model_name="client",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="externalapikey",
            name="name",
            field=models.CharField(
                help_text="Descriptive name for this API key", max_length=255
            ),
        ),
    ]
