# Generated by Django 5.2.7 on 2026-06-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0016_truck_trailer_sovtes_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="externalapikey",
            name="name",
            field=models.CharField(
                help_text="Descriptive name for this API key", max_length=255
            ),
        ),
    ]
