# Generated by Django 5.2.7 on 2026-06-21 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0019_truckunit_timestamps"),
        ("user", "0002_profile_registration_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="truck",
            name="logist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trucks",
                to="user.logistprofile",
            ),
        ),
    ]
