# Generated by Django 5.2.7 on 2026-06-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0020_add_logist_to_truck"),
    ]

    operations = [
        migrations.AddField(
            model_name="trailer",
            name="is_removed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="trailer",
            name="is_removed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="truck",
            name="is_removed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="truck",
            name="is_removed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
