# Generated by Django 5.2.7 on 2026-06-24 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0024_driver_unit_assignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="legal_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
