# Generated by Django 5.2.7 on 2026-06-29 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_sovteswebhookevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filetype',
            name='client',
        ),
        migrations.RemoveField(
            model_name='filetype',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='filetype',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='orderstatus',
            name='client',
        ),
        migrations.RemoveField(
            model_name='orderstatus',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='orderstatus',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='paymenttype',
            name='client',
        ),
        migrations.RemoveField(
            model_name='paymenttype',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='paymenttype',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='taskstatus',
            name='client',
        ),
        migrations.RemoveField(
            model_name='taskstatus',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='taskstatus',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='tasktype',
            name='client',
        ),
        migrations.RemoveField(
            model_name='tasktype',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='tasktype',
            name='updated_at',
        ),
    ]
