# Generated by Django 5.2.7 on 2026-06-29 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_remove_filetype_client_remove_filetype_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platform',
            name='client',
        ),
        migrations.RemoveField(
            model_name='platform',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='platform',
            name='updated_at',
        ),
    ]
