# Generated by Django 5.2.7 on 2026-06-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_remove_platform_client_remove_platform_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktype',
            name='name_uk',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
