# Generated by Django 5.2.7 on 2026-06-29 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_tasktype_name_uk'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
                ('monthly_amount', models.DecimalField(decimal_places=2, help_text='Загальна місячна сума витрат по цьому центру', max_digits=12, verbose_name='Сума на місяць')),
                ('currency', models.CharField(choices=[('UAH', 'UAH'), ('EUR', 'EUR'), ('USD', 'USD')], default='UAH', max_length=3, verbose_name='Валюта')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('client', models.ForeignKey(help_text='Client that owns this record', on_delete=django.db.models.deletion.CASCADE, to='base.client')),
            ],
            options={
                'verbose_name': 'Cost Center',
                'verbose_name_plural': 'Cost Centers',
                'ordering': ['name'],
            },
        ),
    ]
