# Generated by Django 5.2.7 on 2026-06-30 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_order_cost_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ukr', models.CharField(max_length=100, verbose_name='Назва (укр)')),
                ('eng', models.CharField(blank=True, max_length=100, null=True, verbose_name='Назва (англ)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('client', models.ForeignKey(help_text='Client that owns this record', on_delete=django.db.models.deletion.CASCADE, to='base.client')),
            ],
            options={
                'verbose_name': 'Route Category',
                'verbose_name_plural': 'Route Categories',
                'ordering': ['ukr'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='base.routecategory'),
        ),
    ]
