# Generated by Django 5.2.7 on 2026-07-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0033_routecategory_order_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="tender_parent",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name="Tender parent number",
            ),
        ),
    ]
