# Generated by Django 5.2.7 on 2026-06-21 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_profile_registration_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="driverprofile",
            name="sovtes_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
